#node:14
FROM node:14 as build

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm config set registry https://registry.npmjs.org/
RUN npm config set @boozallen-uip:registry https://nexus.dev.bip.va.gov/repository/npm-internal/

RUN npm ci

COPY . ./
RUN npm run build

#nginx:1.19.0
FROM nginx:1.19.0

COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 8080 
CMD ["nginx", "-g", "daemon off;"]